global using System.Linq.Expressions;
global using Core.Entities;
global using Core.DataAccess.Abstract;
global using Microsoft.AspNetCore.Identity;
global using Core.Entities.Concrete;
global using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore;
global using System.ComponentModel.DataAnnotations;
global using Microsoft.AspNetCore.Http;